# Existing Deployment YAML above
---

apiVersion: v1
kind: Service
metadata:
  name: rollingupdate-service                  # Service appended to rolling update deployment for internal comms of pods
  namespace: example-ns
spec:
  type: ClusterIP
  selector:
    tier: backend
  ports:
    - port: 8080
      targetPort: 80
