# Quotas act as a base/reference for the HPA
apiVersion: v1
kind: ResourceQuota
metadata:
   name: rq-project 
   namespace: example-ns
spec:
   hard:
      limits.cpu: 5
      limits.memory: 10Gi
      requests.cpu: 2
      requests.memory: 3Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: dep-project
   namespace: example-ns
spec:
   replicas: 3
   selector:
      matchLabels: 
         tier: backend
   template:
      metadata:
         labels:
            tier: backend
      spec:
         containers:
            - name: nginx
              image: nginx:1.25
              ports:
                 - containerPort: 80


---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
   name: hpa-project
   namespace: example-ns                         # Best practice
spec:
   scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: dep-project                          # Refers the above deployment which is to be scaled
   minReplicas: 1                                # Minimum 1 pod should be present at any time
   maxReplicas: 5                                # HPA can scale the deployment pods upto  maximum of 5 replicas
   metrics:
      - type: Resource
        resource:
           name: cpu
           target:
              type: Utilization
              averageUtilization: 70
              
